from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

import os
from datetime import datetime

# Project Root
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Reports Folder
REPORTS_FOLDER = os.path.join(BASE_DIR, "reports")

os.makedirs(REPORTS_FOLDER, exist_ok=True)


def generate_pdf(patient_name,
                 disease,
                 prediction,
                 probability,
                 risk,
                 recommendation):

    safe_name = patient_name.replace(" ", "_")

    filename = f"{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    pdf_path = os.path.join(REPORTS_FOLDER, filename)

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    story = []

    story.append(
        Paragraph(
            "AI Disease Prediction Report",
            title_style
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    data = [
        ["Patient Name", patient_name],
        ["Disease", disease],
        ["Prediction", prediction],
        ["Probability", f"{probability}%"],
        ["Risk Level", risk],
        ["Generated On", datetime.now().strftime("%d-%m-%Y %H:%M")]
    ]

    table = Table(data, colWidths=[2.5 * inch, 3.5 * inch])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#007BFF")),
        ("TEXTCOLOR", (0, 0), (-1, 0), "white"),
        ("GRID", (0, 0), (-1, -1), 1, "black"),
        ("BACKGROUND", (0, 1), (0, -1), HexColor("#F4F4F4")),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER")
    ]))

    story.append(table)

    story.append(Spacer(1, 0.40 * inch))

    story.append(
        Paragraph(
            "Medical Recommendation",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            recommendation,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    story.append(
        Paragraph(
            "<b>Disclaimer:</b> This report is generated by an AI model. "
            "Please consult a qualified medical professional before making "
            "any healthcare decisions.",
            styles["Italic"]
        )
    )

    doc.build(story)

    print("PDF Path:", pdf_path)
    print("Exists:", os.path.exists(pdf_path))

    return pdf_path