from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)

from reportlab.lib import colors

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.enums import TA_CENTER

from reportlab.lib.units import inch

import os


def generate_pdf(prediction):

    os.makedirs("reports", exist_ok=True)

    pdf_path = f"reports/Loan_Report_{prediction[0]}.pdf"

    doc = SimpleDocTemplate(
        pdf_path,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]

    title_style.alignment = TA_CENTER

    story = []

    # =======================================
    # TITLE
    # =======================================

    story.append(

        Paragraph(
            "Credit AI Loan Prediction Report",
            title_style
        )

    )

    story.append(Spacer(1,0.30*inch))

    # =======================================
    # TABLE DATA
    # =======================================

    table_data=[

        ["Applicant Name",prediction[1]],

        ["Age",prediction[2]],

        ["Gender",prediction[3]],

        ["Education",prediction[4]],

        ["Annual Income",f"₹ {prediction[5]:,.0f}"],

        ["Experience",f"{prediction[6]} Years"],

        ["Home Ownership",prediction[7]],

        ["Loan Amount",f"₹ {prediction[8]:,.0f}"],

        ["Loan Purpose",prediction[9]],

        ["Interest Rate",f"{prediction[10]} %"],

        ["Loan % Income",prediction[11]],

        ["Credit History",prediction[12]],

        ["AI Credit Score",prediction[13]],

        ["Previous Default",prediction[14]],

        ["Prediction",prediction[16]],

        ["Risk",prediction[17]],

        ["Confidence",f"{prediction[18]} %"],

        ["Recommendation",prediction[19]],

        ["Prediction Date",str(prediction[20])]

    ]

    table = Table(

        table_data,

        colWidths=[2.5*inch,4*inch]

    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#0d6efd")),

            ("TEXTCOLOR",(0,0),(0,-1),colors.white),

            ("BACKGROUND",(1,0),(1,-1),colors.whitesmoke),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),

            ("BOTTOMPADDING",(0,0),(-1,-1),8),

            ("TOPPADDING",(0,0),(-1,-1),8)

        ])

    )

    story.append(table)

    story.append(Spacer(1,0.30*inch))

    # =======================================
    # FOOTER
    # =======================================

    footer = Paragraph(

        "<b>Generated by Credit AI System</b><br/>"
        "This report is generated using Machine Learning.",

        styles["Normal"]

    )

    story.append(footer)

    doc.build(story)

    return pdf_path